### ISSUE TITLE
Extend decoder to accept longs 

### ISSUE THREAD

**Issue by izemlyanskiy** [canozbey/finite-state-rice-decoder#1]
Hello! Thank you for this work. It was my pleasure to read through your paper. 
I just wonder, is it possible to extend this approach to accept not only ints but longs as well? 
Per my understanding, we don't need any new states because we've already covered all byte position cases, but we have to take into account that we might stay in state Q3/R3 several times, correct? 
And probably some other adjustments for the math for c,d and m... 
Did you have any thoughts or, maybe, some POC for longs? 
I'll be more than happy if you share any information about that. Thank you in advance!

**Comment by canozbey** [comment]
Thank you for your interest. It is in fact the other way around. If we apply this approach based on longs, then it is more likely that we visit Q7/R7 states provided that an optimal Golomb parameter is used. This is because the alignment would be based on fixed 64-bit words, and Q/R parts would be relatively shorter. For the R part to exceed 64 bits, for example, the distribution of integers must be quite flat so that it may produce very large integers. On the other side, the Q part is expected to be much shorter if the Golomb parameter is properly selected. Of course, I do not know much about your use case. But, I suspect that an implementation based on longs would be more advantageous than byte-based implementation (a short-based implementation may be better if you have a flat distribution).

Still, it is easy to adapt the current model to be applied on longs. All you need to do is to initialize c as 64 instead of 8 and change the other assignments accordingly. For instance, based-2 logarithm of a current byte must be calculated at certain states, and this operation must be applied to a long instead of a byte. In this implementation, it is simply done by an array lookup as there are only 256 possible byte values. For longs, an efficient on-the-fly logarithm calculation is needed, as it won't be wise to store an array of size 2^64. Likewise, you also need to update modular arithmetic operations changing byte_i mod 2^(8-d) to long_i mod 2^(64-d), and so on. Also, 7s must be changed to 63s.

Hope this helps!

**Comment by canozbey** [comment]
As I now notice, I may have misunderstood your question. If you are referring to compressing longs instead of ints and still executing a byte-based decoding, then there is not much to worry about. Staying Q3/R3 states will not cause any problem as they have self-loops. I think you only need to change the types of q, k, r to long in StateVaribles class so that the operation ((q << k) | r) will return a long. Also, you may need to change a couple of data types in the State class. But it should not be so problematic. 

Good luck!

**Comment by izemlyanskiy** [comment]
thank you for this work and for merging my PR #2!
